# Generated by Django 2.1.15 on 2020-06-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('contactinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApplication.ContactInfos')),
                ('rollno', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            bases=('testApplication.contactinfos',),
        ),
        migrations.CreateModel(
            name='Teacher1',
            fields=[
                ('contactinfos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApplication.ContactInfos')),
                ('subject', models.CharField(max_length=128)),
                ('salary', models.FloatField()),
            ],
            bases=('testApplication.contactinfos',),
        ),
    ]
